import type { EventLogEntry } from "./app-events";
import type { DevicePairingList } from "./controllers/devices";
import type { ExecApprovalRequest } from "./controllers/exec-approval";
import type { ExecApprovalsFile, ExecApprovalsSnapshot } from "./controllers/exec-approvals";
import type { SkillMessage } from "./controllers/skills";
import type { GatewayBrowserClient, GatewayHelloOk } from "./gateway";
import type { Tab } from "./navigation";
import type { UiSettings } from "./storage";
import type { ThemeMode } from "./theme";
import type { ThemeTransitionContext } from "./theme-transition";
import type {
  AgentsListResult,
  ChannelsStatusSnapshot,
  ConfigSnapshot,
  CronJob,
  CronRunLogEntry,
  CronStatus,
  HealthSnapshot,
  LogEntry,
  LogLevel,
  NostrProfile,
  PresenceEntry,
  SessionsListResult,
  SkillStatusReport,
  StatusSummary,
} from "./types";
import type { ChatAttachment, ChatQueueItem, CronFormState } from "./ui-types";
import type { NostrProfileFormState } from "./views/channels.nostr-profile-form";
import type { SkillDetailTab } from "./views/skills";

export type AppViewState = {
  settings: UiSettings;
  password: string;
  tab: Tab;
  onboarding: boolean;
  basePath: string;
  connected: boolean;
  theme: ThemeMode;
  themeResolved: "light" | "dark";
  hello: GatewayHelloOk | null;
  lastError: string | null;
  eventLog: EventLogEntry[];
  assistantName: string;
  assistantAvatar: string | null;
  assistantAgentId: string | null;
  sessionKey: string;
  chatLoading: boolean;
  chatSending: boolean;
  chatMessage: string;
  chatAttachments: ChatAttachment[];
  chatMessages: unknown[];
  chatToolMessages: unknown[];
  chatStream: string | null;
  chatRunId: string | null;
  chatStreamStartedAt: number | null;
  chatAvatarUrl: string | null;
  chatThinkingLevel: string | null;
  chatThinkingActive: boolean;
  chatThinkingSteps: import("./components/ThinkingIndicator").ThinkingStep[];
  chatThinkingCurrentStepIndex: number;
  chatThinkingStartedAt: number | null;
  chatThinkingCompletedAt: number | null;
  chatThinkingSummary: string | null;
  chatQueue: ChatQueueItem[];
  chatScrolledUp: boolean;
  nodesLoading: boolean;
  nodes: Array<Record<string, unknown>>;
  devicesLoading: boolean;
  devicesError: string | null;
  devicesList: DevicePairingList | null;
  execApprovalsLoading: boolean;
  execApprovalsSaving: boolean;
  execApprovalsDirty: boolean;
  execApprovalsSnapshot: ExecApprovalsSnapshot | null;
  execApprovalsForm: ExecApprovalsFile | null;
  execApprovalsSelectedAgent: string | null;
  execApprovalsTarget: "gateway" | "node";
  execApprovalsTargetNodeId: string | null;
  execApprovalQueue: ExecApprovalRequest[];
  execApprovalBusy: boolean;
  execApprovalError: string | null;
  pendingGatewayUrl: string | null;
  configLoading: boolean;
  configRaw: string;
  configRawOriginal: string;
  configValid: boolean | null;
  configIssues: unknown[];
  configSaving: boolean;
  configApplying: boolean;
  updateRunning: boolean;
  configSnapshot: ConfigSnapshot | null;
  configSchema: unknown | null;
  configSchemaLoading: boolean;
  configUiHints: Record<string, unknown>;
  configForm: Record<string, unknown> | null;
  configFormOriginal: Record<string, unknown> | null;
  configFormMode: "form" | "raw";
  channelsLoading: boolean;
  channelsSnapshot: ChannelsStatusSnapshot | null;
  channelsError: string | null;
  channelsLastSuccess: number | null;
  whatsappLoginMessage: string | null;
  whatsappLoginQrDataUrl: string | null;
  whatsappLoginConnected: boolean | null;
  whatsappBusy: boolean;
  nostrProfileFormState: NostrProfileFormState | null;
  nostrProfileAccountId: string | null;
  configFormDirty: boolean;
  presenceLoading: boolean;
  presenceEntries: PresenceEntry[];
  presenceError: string | null;
  presenceStatus: string | null;
  agentsLoading: boolean;
  agentsList: AgentsListResult | null;
  agentsError: string | null;
  sessionsLoading: boolean;
  sessionsResult: SessionsListResult | null;
  sessionsError: string | null;
  sessionsFilterActive: string;
  sessionsFilterLimit: string;
  sessionsIncludeGlobal: boolean;
  sessionsIncludeUnknown: boolean;
  cronLoading: boolean;
  cronJobs: CronJob[];
  cronStatus: CronStatus | null;
  cronError: string | null;
  cronForm: CronFormState;
  cronRunsJobId: string | null;
  cronRuns: CronRunLogEntry[];
  cronBusy: boolean;
  skillsLoading: boolean;
  skillsReport: SkillStatusReport | null;
  skillsError: string | null;
  skillsFilter: string;
  skillEdits: Record<string, string>;
  skillMessages: Record<string, SkillMessage>;
  skillsBusyKey: string | null;
  skillsActiveFilter: "all" | "active" | "needs-setup" | "disabled";
  skillsSelectedSkill: string | null;
  skillsSelectedSkillTab: SkillDetailTab;
  debugLoading: boolean;
  debugStatus: StatusSummary | null;
  debugHealth: HealthSnapshot | null;
  debugModels: unknown[];
  debugHeartbeat: unknown | null;
  debugCallMethod: string;
  debugCallParams: string;
  debugCallResult: string | null;
  debugCallError: string | null;
  logsLoading: boolean;
  logsError: string | null;
  logsFile: string | null;
  logsEntries: LogEntry[];
  logsFilterText: string;
  logsLevelFilters: Record<LogLevel, boolean>;
  logsAutoFollow: boolean;
  logsTruncated: boolean;
  client: GatewayBrowserClient | null;
  connect: () => void;
  setTab: (tab: Tab) => void;
  setTheme: (theme: ThemeMode, context?: ThemeTransitionContext) => void;
  applySettings: (next: UiSettings) => void;
  loadOverview: () => Promise<void>;
  loadAssistantIdentity: () => Promise<void>;
  loadCron: () => Promise<void>;
  handleWhatsAppStart: (force: boolean) => Promise<void>;
  handleWhatsAppWait: () => Promise<void>;
  handleWhatsAppLogout: () => Promise<void>;
  handleChannelConfigSave: () => Promise<void>;
  handleChannelConfigReload: () => Promise<void>;
  handleNostrProfileEdit: (accountId: string, profile: NostrProfile | null) => void;
  handleNostrProfileCancel: () => void;
  handleNostrProfileFieldChange: (field: keyof NostrProfile, value: string) => void;
  handleNostrProfileSave: () => Promise<void>;
  handleNostrProfileImport: () => Promise<void>;
  handleNostrProfileToggleAdvanced: () => void;
  handleToggleChannel: (channelKey: string, enabled: boolean) => Promise<void>;
  // Channel setup modal state
  channelSetupModalOpen: boolean;
  channelSetupModalKey: string | null;
  channelSetupModalFormData: Record<string, unknown>;
  channelSetupModalSubmitting: boolean;
  channelSetupModalError: string | null;
  handleChannelSetupOpen: (channelKey: string) => Promise<void>;
  handleChannelSetupClose: () => void;
  handleChannelSetupFieldChange: (fieldName: string, value: unknown) => void;
  handleChannelSetupSubmit: (channelKey: string, config: Record<string, unknown>) => Promise<void>;
  handleExecApprovalDecision: (decision: "allow-once" | "allow-always" | "deny") => Promise<void>;
  handleGatewayUrlConfirm: () => void;
  handleGatewayUrlCancel: () => void;
  handleConfigLoad: () => Promise<void>;
  handleConfigSave: () => Promise<void>;
  handleConfigApply: () => Promise<void>;
  handleConfigFormUpdate: (path: string, value: unknown) => void;
  handleConfigFormModeChange: (mode: "form" | "raw") => void;
  handleConfigRawChange: (raw: string) => void;
  handleInstallSkill: (key: string) => Promise<void>;
  handleUpdateSkill: (key: string) => Promise<void>;
  handleToggleSkillEnabled: (key: string, enabled: boolean) => Promise<void>;
  handleUpdateSkillEdit: (key: string, value: string) => void;
  handleSaveSkillApiKey: (key: string, apiKey: string) => Promise<void>;
  handleCronToggle: (jobId: string, enabled: boolean) => Promise<void>;
  handleCronRun: (jobId: string) => Promise<void>;
  handleCronRemove: (jobId: string) => Promise<void>;
  handleCronAdd: () => Promise<void>;
  handleCronRunsLoad: (jobId: string) => Promise<void>;
  handleCronFormUpdate: (path: string, value: unknown) => void;
  handleSessionsLoad: () => Promise<void>;
  handleSessionsPatch: (key: string, patch: unknown) => Promise<void>;
  handleLoadNodes: () => Promise<void>;
  handleLoadPresence: () => Promise<void>;
  handleLoadSkills: () => Promise<void>;
  handleLoadDebug: () => Promise<void>;
  handleLoadLogs: () => Promise<void>;
  handleDebugCall: () => Promise<void>;
  handleRunUpdate: () => Promise<void>;
  setPassword: (next: string) => void;
  setSessionKey: (next: string) => void;
  setChatMessage: (next: string) => void;
  handleChatSend: () => Promise<void>;
  handleChatAbort: () => Promise<void>;
  handleChatSelectQueueItem: (id: string) => void;
  handleChatDropQueueItem: (id: string) => void;
  handleChatClearQueue: () => void;
  handleLogsFilterChange: (next: string) => void;
  handleLogsLevelFilterToggle: (level: LogLevel) => void;
  handleLogsAutoFollowToggle: (next: boolean) => void;
  handleCallDebugMethod: (method: string, params: string) => Promise<void>;
  // Commands menu state
  commandsMenuOpen: boolean;
  handleToggleCommandsMenu: () => void;
  // Voice recorder state
  voiceRecorderOpen: boolean;
  handleToggleVoiceRecorder: () => void;
  handleScrollToBottom: () => void;
  // Config documentation panel state
  configDocPanelOpen: boolean;
  configDocSearchQuery: string;
  handleToggleConfigDocPanel: () => void;
  handleConfigDocSearchChange: (query: string) => void;
  handleInsertConfigTemplate: (template: string) => void;
  handleInsertConfigField: (field: string) => void;
  // Compliance state
  complianceLoading: boolean;
  complianceError: string | null;
  complianceStatus: import("./types").ComplianceStatus | null;
  complianceReports: import("./types").ComplianceReport[];
  complianceSelectedFramework: import("./types").ComplianceFramework | "all";
  complianceActiveTab: "overview" | "reports" | "violations" | "settings";
  handleComplianceTabChange: (tab: "overview" | "reports" | "violations" | "settings") => void;
  handleComplianceFrameworkChange: (framework: import("./types").ComplianceFramework | "all") => void;
  handleComplianceRefresh: () => Promise<void>;
  handleComplianceGenerateReport: (framework: import("./types").ComplianceFramework) => Promise<void>;
  handleComplianceExportData: () => Promise<void>;
  handleComplianceViolationAcknowledge: (id: string) => Promise<void>;
  handleComplianceViolationResolve: (id: string) => Promise<void>;
  handleSkillsActiveFilterChange: (filter: "all" | "active" | "needs-setup" | "disabled") => void;
  handleSkillsSelectSkill: (skillKey: string | null) => void;
  handleSkillsSelectSkillTab: (tab: import("./views/skills").SkillDetailTab) => void;
  analyzingSkill: string | null;
  skillAnalysis: Record<string, { securityScan?: import("./types").SkillSecurityScan; richDescription?: import("./types").RichSkillDescription }>;
  handleAnalyzeSkill: (skillKey: string, filePath: string) => Promise<void>;
  handleSendChat: (messageOverride?: string, opts?: { restoreDraft?: boolean }) => Promise<void>;
  handleAbortChat: () => Promise<void>;
  removeQueuedMessage: (id: string) => void;
  handleChatScroll: (event: Event) => void;
  resetToolStream: () => void;
  resetChatScroll: () => void;
  exportLogs: (lines: string[], label: string) => void;
  handleLogsScroll: (event: Event) => void;
  handleOpenSidebar: (content: string) => void;
  handleCloseSidebar: () => void;
  handleSplitRatioChange: (ratio: number) => void;
  // ModelSelector state
  selectedProvider: string | null;
  selectedModel: string | null;
  modelLoading: boolean;
  configuredProviders: import("./components/model-selector.js").ModelProvider[] | null;
  providersLoading: boolean;
  loadCurrentModel: () => Promise<void>;
  loadConfiguredProviders: () => Promise<void>;
  // Models page state
  modelsLoading: boolean;
  modelsError: string | null;
  modelsProviders: import("./components/provider-card.js").ProviderCardData[] | null;
  modelsSearchQuery: string;
  configuredProfileIds: string[];
  modelsShowAddForm: string | null;
  handleModelsRefresh: () => Promise<void>;
  handleModelsTest: (profileId: string, credential: unknown) => Promise<void>;
  handleModelsSave: (profileId: string, credential: unknown, email?: string) => Promise<void>;
  handleModelsRemove: (profileId: string) => Promise<void>;
  // Environment variables state
  envVars: Array<{
    key: string;
    encrypted: boolean;
    createdAt: number;
    updatedAt: number;
    hasValue: boolean;
    isSensitive: boolean;
  }>;
  envLoading: boolean;
  envSaving: boolean;
  envError: string;
  envModalOpen: boolean;
  envEditingVar: { key: string } | null;
  envKeyInput: string;
  envValueInput: string;
  envEncryptInput: boolean;
  envValidationError: string;
  handleEnvLoad: () => Promise<void>;
  handleEnvModalOpen: (editVar?: { key: string }) => void;
  handleEnvModalClose: () => void;
  handleEnvKeyInput: (value: string) => void;
  handleEnvValueInput: (value: string) => void;
  handleEnvEncryptInput: (value: boolean) => void;
  handleEnvValidationError: (error: string) => void;
  handleEnvSave: () => Promise<void>;
  handleEnvDelete: (key: string) => Promise<void>;
  // Gateway restart
  restarting: boolean;
  handleRestart: () => Promise<void>;
  // News state
  newsLoading: boolean;
  newsError: string | null;
  newsItems: import("./views/news").NewsItem[];
  newsSelectedItem: import("./views/news").NewsItem | null;
  newsFilter: "all" | "today" | "week" | "month";
  newsSearchQuery: string;
  newsSources: string[];
  newsSelectedSources: string[];
  handleNewsLoad: () => Promise<void>;
  handleNewsRefresh: () => Promise<void>;
  handleNewsFilterChange: (filter: "all" | "today" | "week" | "month") => void;
  handleNewsSearchChange: (query: string) => void;
  handleNewsSourceToggle: (source: string, enabled: boolean) => void;
  handleNewsSelectItem: (item: import("./views/news").NewsItem | null) => void;
  // Wizard state
  wizardOpen: boolean;
  wizardProviderId: string | null;
  wizardProviderName: string | null;
  handleModelsConfigure: (providerId: string) => void;
  handleModelsManage: (providerId: string) => void;
  handleModelsSearchChange: (query: string) => void;
  handleWizardClose: () => void;
  handleWizardSave: (e: CustomEvent) => Promise<void>;
  handleOAuthStart: (e: CustomEvent) => void;
  // MCP state
  mcpLoading: boolean;
  mcpError: string | null;
  mcpServers: Array<{ id: string; name: string; url: string; status: string; category?: string; description?: string; transport?: string }>;
  mcpSelectedServer: string | null;
  mcpSearchQuery: string;
  mcpSelectedCategory: string | null;
  mcpShowAddModal: boolean;
  mcpNewServerName: string;
  mcpNewServerUrl: string;
  mcpNewServerCategory: string;
  // Marketplace state
  mcpShowMarketplace: boolean;
  mcpMarketplace: Array<{ id: string; name: string; description: string; url: string; transport: string; category: string; installCommand?: string; tags?: string[]; official?: boolean }>;
  mcpMarketplaceLoading: boolean;
  mcpMarketplaceCategories: Array<{ id: string; name: string; count: number }>;
  mcpMarketplaceTags: string[];
  mcpMarketplaceSearchQuery: string;
  mcpMarketplaceSelectedCategory: string | null;
  mcpMarketplaceSelectedTag: string | null;
  mcpMarketplaceOfficialOnly: boolean;
  // Handlers
  handleMcpLoad: () => Promise<void>;
  handleMcpAddServer: (name: string, url: string, transport: string, category?: string, description?: string) => Promise<void>;
  handleMcpRemoveServer: (id: string) => Promise<void>;
  handleMcpToggleServer: (id: string, enabled: boolean) => Promise<void>;
  handleMcpSearchChange: (query: string) => void;
  handleMcpCategoryChange: (category: string | null) => void;
  handleMcpSelectServer: (id: string | null) => void;
  handleMcpOpenAddModal: () => void;
  handleMcpCloseAddModal: () => void;
  handleMcpUpdateNewServerName: (value: string) => void;
  handleMcpUpdateNewServerUrl: (value: string) => void;
  handleMcpUpdateNewServerCategory: (value: string) => void;
  // Marketplace handlers
  handleMcpShowMarketplace: () => Promise<void>;
  handleMcpCloseMarketplace: () => void;
  handleMcpInstallFromMarketplace: (marketplaceId: string) => Promise<void>;
  handleMcpMarketplaceSearchChange: (query: string) => Promise<void>;
  handleMcpMarketplaceCategoryChange: (category: string | null) => Promise<void>;
  handleMcpMarketplaceTagChange: (tag: string | null) => Promise<void>;
  handleMcpMarketplaceOfficialToggle: () => Promise<void>;
  handleMcpLoadMarketplaceCategories: () => Promise<void>;
  handleMcpResetMarketplaceFilters: () => Promise<void>;
  // Containers state
  containersLoading: boolean;
  containersError: string | null;
  containers: Array<{ id: string; name: string; status: string; image: string }>;
  handleContainersLoad: () => Promise<void>;
  handleContainerStart: (id: string) => Promise<void>;
  handleContainerStop: (id: string) => Promise<void>;
  handleContainerRestart: (id: string) => Promise<void>;
  handleContainerLogs: (id: string) => Promise<void>;
  // Security state
  securityLoading: boolean;
  securityError: string | null;
  securityStatus: { overallScore: number; lastScan: Date | null; vulnerabilities: number } | null;
  handleSecurityLoad: () => Promise<void>;
  handleSecurityScan: () => Promise<void>;
  // Features state
  featuresLoading: boolean;
  featuresError: string | null;
  featuresList: Array<{
    id: string;
    name: string;
    description: string;
    icon: string;
    status: "enabled" | "disabled" | "needs_config" | "unavailable";
    configurable: boolean;
    category: "speech" | "channels" | "ai" | "integrations" | "tools";
    configFields?: Array<{
      key: string;
      label: string;
      type: "text" | "password" | "select" | "toggle";
      placeholder?: string;
      options?: { value: string; label: string }[];
      required?: boolean;
    }>;
  }>;
  featuresSearchQuery: string;
  featuresSelectedCategory: string | null;
  featuresSelectedFeature: string | null;
  featuresConfigModalOpen: boolean;
  featuresConfigModalFeature: string | null;
  featuresConfigFormData: Record<string, unknown>;
  featuresConfigSubmitting: boolean;
  handleFeaturesLoad: () => Promise<void>;
  handleFeaturesToggle: (id: string, enabled: boolean) => Promise<void>;
  handleFeaturesConfigure: (id: string, config: Record<string, unknown>) => Promise<void>;
  handleFeaturesSearchChange: (query: string) => void;
  handleFeaturesCategoryChange: (category: string | null) => void;
  handleFeaturesSelectFeature: (id: string | null) => void;
  handleFeaturesOpenConfigModal: (id: string) => void;
  handleFeaturesCloseConfigModal: () => void;
  handleFeaturesConfigFormChange: (key: string, value: unknown) => void;
  // OpenCode state
  opencodeStatus: { enabled: boolean; runtimeAvailable: boolean; runtimeType: string | null; activeTasks: number; totalTasks: number; pendingApprovals: number } | null;
  opencodeTasks: Array<{ id: string; prompt: string; status: string; createdAt: string; startedAt?: string; completedAt?: string; containerId?: string; workspacePath?: string; approvedBy?: string; approvedAt?: string; result?: string; error?: string; securityFlags?: string[] }>;
  opencodeSelectedTask: { id: string; prompt: string; status: string; createdAt: string; startedAt?: string; completedAt?: string; containerId?: string; workspacePath?: string; approvedBy?: string; approvedAt?: string; result?: string; error?: string; securityFlags?: string[] } | null;
  opencodeTaskInput: string;
  opencodeTaskCreating: boolean;
  opencodeConfig: Record<string, unknown>;
  opencodeConfigLoading: boolean;
  opencodeConfigError: string | null;
  opencodeConfigDirty: boolean;
  opencodeConfigSaving: boolean;
  opencodeSettingsSection: string;
  opencodeSecuritySection: string;
  opencodeSecurityConfig: Record<string, unknown>;
  opencodeSecurityDirty: boolean;
  opencodeSecuritySaving: boolean;
  opencodeAuditLog: Array<{ id: string; timestamp: string; action: string; user?: string; taskId?: string; details: string; severity: string }>;
  opencodeAuditLoading: boolean;
  // OpenCode handlers
  handleOpencodeStatusLoad: () => Promise<void>;
  handleOpencodeTasksLoad: () => Promise<void>;
  handleOpencodeTaskInputChange: (value: string) => void;
  handleOpencodeTaskCreate: () => Promise<void>;
  handleOpencodeTaskSelect: (task: { id: string; prompt: string; status: string; createdAt: string } | null) => void;
  handleOpencodeTaskApprove: (taskId: string) => Promise<void>;
  handleOpencodeTaskCancel: (taskId: string) => Promise<void>;
  handleOpencodeTaskLogs: (taskId: string) => Promise<void>;
  handleOpencodeTaskDownload: (taskId: string) => Promise<void>;
  handleOpencodeConfigLoad: () => Promise<void>;
  handleOpencodeConfigSave: () => Promise<void>;
  handleOpencodeConfigReset: () => void;
  handleOpencodeConfigChange: (key: string, value: unknown) => void;
  handleOpencodeSettingsSectionChange: (section: string) => void;
  handleOpencodeSecurityLoad: () => Promise<void>;
  handleOpencodeSecuritySave: () => Promise<void>;
  handleOpencodeSecurityReset: () => void;
  handleOpencodeSecurityChange: (key: string, value: unknown) => void;
  handleOpencodeSecuritySectionChange: (section: string) => void;
  handleOpencodeAuditLoad: () => Promise<void>;
  handleOpencodeAuditRefresh: () => Promise<void>;
  handleOpencodeAuditExport: () => Promise<void>;
};
